### ISSUE TITLE
bug: miniserve process keeps TCP sockets open until it runs out of FDs

### ISSUE THREAD

**Issue by OliverNChalk** [svenstaro/miniserve#1456] opened 2024-10-01 22:18 UTC
Output of `lsof -i -a -p <miniserve>`
```
COMMAND      PID   USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
miniserve 894772 ubuntu    9u  IPv6 49383209      0t0  TCP *:http-alt (LISTEN)
miniserve 894772 ubuntu   10u  IPv4 49383210      0t0  TCP *:http-alt (LISTEN)
miniserve 894772 ubuntu   21u  IPv4 49385603      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:38372 (ESTABLISHED)
miniserve 894772 ubuntu   22u  IPv4 49385605      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:38380 (ESTABLISHED)
miniserve 894772 ubuntu   23u  IPv4 49385164      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:42922 (ESTABLISHED)
miniserve 894772 ubuntu   24u  IPv4 49385291      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:52666 (ESTABLISHED)
miniserve 894772 ubuntu   25u  IPv4 49386277      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:47126 (ESTABLISHED)
miniserve 894772 ubuntu   26u  IPv4 49387077      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:52840 (ESTABLISHED)
miniserve 894772 ubuntu   27u  IPv4 49387189      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:56366 (ESTABLISHED)
miniserve 894772 ubuntu   28u  IPv4 49387222      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:58086 (ESTABLISHED)
miniserve 894772 ubuntu   29u  IPv4 49387224      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:58088 (ESTABLISHED)
miniserve 894772 ubuntu   30u  IPv4 49387264      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:48436 (ESTABLISHED)
miniserve 894772 ubuntu   31u  IPv4 49387365      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:56094 (ESTABLISHED)
miniserve 894772 ubuntu   32u  IPv4 49389214      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:58286 (ESTABLISHED)
miniserve 894772 ubuntu   33u  IPv4 49389216      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:58300 (ESTABLISHED)
miniserve 894772 ubuntu   34u  IPv4 49388405      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:38720 (ESTABLISHED)
miniserve 894772 ubuntu   35u  IPv4 49389370      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:37698 (ESTABLISHED)
miniserve 894772 ubuntu   36u  IPv4 49389477      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:50886 (ESTABLISHED)
miniserve 894772 ubuntu   37u  IPv4 49389536      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:39490 (ESTABLISHED)
miniserve 894772 ubuntu   38u  IPv4 50032939      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:58132 (ESTABLISHED)
miniserve 894772 ubuntu   39u  IPv4 50032210      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:58140 (ESTABLISHED)
miniserve 894772 ubuntu   40u  IPv4 50032272      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:51088 (ESTABLISHED)
miniserve 894772 ubuntu   41u  IPv4 50033043      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:50814 (ESTABLISHED)
miniserve 894772 ubuntu   42u  IPv4 50034440      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:46436 (ESTABLISHED)
miniserve 894772 ubuntu   43u  IPv4 50035014      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:46452 (ESTABLISHED)
miniserve 894772 ubuntu   44u  IPv4 50034489      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:59474 (ESTABLISHED)
miniserve 894772 ubuntu   45u  IPv4 50035747      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:42522 (ESTABLISHED)
miniserve 894772 ubuntu   47u  IPv4 50035935      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:40404 (ESTABLISHED)
miniserve 894772 ubuntu   48u  IPv4 50257332      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:44458 (ESTABLISHED)
miniserve 894772 ubuntu   49u  IPv4 50256728      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:44466 (ESTABLISHED)
miniserve 894772 ubuntu   50u  IPv4 50256788      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:60226 (ESTABLISHED)
miniserve 894772 ubuntu   51u  IPv4 50258083      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:50620 (ESTABLISHED)
miniserve 894772 ubuntu   52u  IPv4 50257798      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:38276 (ESTABLISHED)
miniserve 894772 ubuntu   53u  IPv4 50257803      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:38292 (ESTABLISHED)
miniserve 894772 ubuntu   54u  IPv4 50260410      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:48734 (ESTABLISHED)
miniserve 894772 ubuntu   55u  IPv4 50265182      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:35618 (ESTABLISHED)
miniserve 894772 ubuntu   56u  IPv4 50266919      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:32994 (ESTABLISHED)
miniserve 894772 ubuntu   57u  IPv4 50269360      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:54246 (ESTABLISHED)
miniserve 894772 ubuntu   58u  IPv4 50905012      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:58996 (ESTABLISHED)
miniserve 894772 ubuntu   59u  IPv4 50905015      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:59002 (ESTABLISHED)
miniserve 894772 ubuntu   60u  IPv4 50905043      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:43944 (ESTABLISHED)
miniserve 894772 ubuntu   61u  IPv4 50906133      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:42842 (ESTABLISHED)
miniserve 894772 ubuntu   62u  IPv4 50908224      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:59160 (ESTABLISHED)
miniserve 894772 ubuntu   63u  IPv4 50908226      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:59166 (ESTABLISHED)
miniserve 894772 ubuntu   64u  IPv4 50908396      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:35436 (ESTABLISHED)
miniserve 894772 ubuntu   65u  IPv4 50908525      0t0  TCP ip-10-69-0-1.ap-northeast-1.compute.internal:http-alt->ip-10-69-0-3.ap-northeast-1.compute.internal:33630 (ESTABLISHED)
```

Miniserve arguments:
```
/usr/local/bin/miniserve \
    --upload-files \
    -- \
    /home/ubuntu/binaries
```

**Comment by svenstaro** [comment] 2024-10-02 03:18
That's really odd. I don't have this behavior:
```
COMMAND   PID      USER FD   TYPE DEVICE SIZE/OFF NODE NAME
miniserve 783 miniserve 9u  IPv6  11615      0t0  TCP localhost:search-agent (LISTEN)
```

**Comment by svenstaro** [comment] 2024-10-07 13:22
Closing this for now. I can't reproduce this at all, unfortunately.

**Closed** 2024-10-07 13:21 UTC
