### ISSUE TITLE
Does it support hiding some files?

### ISSUE THREAD

**Issue by Zruto** [svenstaro/miniserve#1307] opened 2024-01-09 09:46 UTC

**Comment by svenstaro** [comment] 2024-01-09 13:08
Is this the same as #1304?

**Comment by Zruto** [comment] 2024-01-09 15:12
Yes, is this feature available now?

**Comment by svenstaro** [comment] 2024-01-09 15:27
No, would you like to make a specification and maybe even try to take a stab at implementing this?

**Comment by Zruto** [comment] 2024-01-09 15:47
Sorry, I'm not very good at it

**Comment by svenstaro** [comment] 2024-01-13 04:03
Closing as a duplicate of #1304.

**Closed by svenstaro** 2024-01-13 04:03 UTC

**Comment by svenstaro** [comment] 2024-01-13 07:45
Oh, just remembered, you might be interested in miniserve's feature to hide .dotfiles by default.
