### ISSUE TITLE
Feature suggestion: Config file

### ISSUE THREAD

**Issue by mdnava** [svenstaro/miniserve#809] opened 2022-06-07 18:47 UTC
Hi.. I just found this program by chance.. pretty cool utility you've made.

If I may suggest something. It would be a great feature to have available a **config file** (in the same location as the binary) where to set defaults; something like "miniserve.conf"... And perhaps be able to set a different location for this file with an environment var. Of course, options given by command line arguments should take precedence over the config file.

An icon for the binary would also be a good idea, so it's shown on ConEmu tabs.
I tried adding one manually, but for some reason the program stopped working,

**Comment by stappersg** [comment] 2022-12-24 17:37
Please close as duplicate of #101

**Closed** 2022-12-24 17:52 UTC
